# Generated by Django 5.1.1 on 2024-09-17 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0002_museum_artworks_museum_category_museum_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='museum',
            name='artworks',
        ),
    ]
