# Generated by Django 5.1.1 on 2024-09-17 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
        ('artwork', '0003_artwork_advancedinfo_artwork_artist_artwork_date_and_more'),
        ('image', '0003_alter_image_museum'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artist.artist'),
        ),
        migrations.AddField(
            model_name='image',
            name='artwork',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.artwork'),
        ),
    ]
