# Generated by Django 5.1.1 on 2024-09-17 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0001_initial'),
        ('museum', '0003_remove_museum_artworks'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='museum',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='museum.museum'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
