# Generated by Django 5.1.1 on 2024-09-17 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
        ('artwork', '0002_artwork_museum_alter_artwork_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='advancedInfo',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='artwork',
            name='artist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='artist.artist'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='artwork',
            name='dimensions',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='artwork',
            name='preview',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='artwork',
            name='technique',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
