# Generated by Django 5.1.1 on 2024-09-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0003_artwork_advancedinfo_artwork_artist_artwork_date_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likedArtowks',
            field=models.ManyToManyField(related_name='usersLiked', to='artwork.artwork'),
        ),
    ]
