# Generated by Django 5.1.1 on 2024-09-17 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0003_artwork_advancedinfo_artwork_artist_artwork_date_and_more'),
        ('comment', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='artwork',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='artwork.artwork'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
